<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Encrypt',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

        $items['success'] = array(
            'title' => 'Success',
            'page callback' => 'cipher_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'Your Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter your word or phrase here.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

// function cipher_form_submit($form, &$form_state) {
//     $phrase = $form_state['values']['phrase'];
//     $phrase_lower = strtolower($phrase);
//
// }
