<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Encrypt',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

        $items['success'] = array(
            'title' => 'Success',
            'page callback' => 'cipher_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'Your Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter your word or phrase here.'),
    );

    $form['direction'] = array(
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter which direction you would like to encrypt in.'),
    );

    $form['shift'] = array(
        '#title' => 'Shift',
        '#type' => 'textfield',
        '#description' => t('Please enter how many letters you would like to shift by.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $phrase = $form_state['values']['phrase'];
    $direction = $form_state['values']['direction'];
    $shift = $form_state['values']['shift'];
    $letters = str_split(strtoupper($phrase));
    $alphas = range('A', 'Z');
    $encrypted = [];

    foreach($letters as $letter) {
        if(in_array($letter, $alphas)) {
            $letter_key = array_search($letter, $alphas);
            if($direction == 'left') {
                $encrypt_key = $letter_key - $shift;
                $remainder_key = $encrypt_key % 25;
                if($encrypt_key < 0) {
                    $abs_key = abs($remainder_key);
                    $reverse_alphas = array_reverse($alphas, true);
                    $new_letter = $reverse_alphas[$abs_key];
                    array_push($encrypted, $new_letter);
                } else {
                    $new_letter = $alphas[$remainder_key];
                    array_push($encrypted, $new_letter);
                }
            } else { //direction == right
                    $encrypt_key = $letter_key . $shift;
                    $remainder_key = $encrypt_key % 25;
                    $new_letter = $alphas[$remainder_key];
                    array_push($encrypted, $new_letter);
                }
        } else {
            array_push($encrypted, $letter);
        }
    }

    $result = strtolower(implode("", $encrypted));
    $_SESSION['cipher_output'] = $result;
    $form_state['redirect'] = 'success';
}

function cipher_success() {
    $encrypted_phrase = $_SESSION['cipher_output'];
    return "<p>Your final phrase is: $encrypted_phrase</p>";

}
